Vue Basics
js-tasks-ru/vue-20220125_andrei-navrotski pull request #2
Opened 2022-01-30 22:11 UTC by Naurotski

2022-01-30 22:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-01-31 22:11 UTC, ShGKme requested changes
В `03-MarkedList` требуется вместо вычисления отфильтрованного списка и последующего поиска, лучше сразу подготовить данные к выводу, где есть и email, и данные о маркировке этого email.

2022-01-31 22:11 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
>      </div>
У текстовой интерполяции обычно принято добавлять пробелы в скобках: `{{ counter }}`

2022-01-31 22:11 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
>          </div>
👍

2022-01-31 22:11 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
В задаче требуется именно отметить выбранные email-ы. При текущем решении email-ы не отмечаются, а фильтруются. Использовать такой результат напрямую не получается, из-за чего в шаблоне приходится опять перебирать массив.

В итоге сначала перебирается весь массив почт, а потом для каждой почте при выводе опять перебирается массив уже отфильтрованных почт с проверкой, а нет ли там уже проверенной ранее почты.

Такое решение и не очень оптимальное. Но хуже, что при таком решении требуется описывать логику решения в шаблоне.

2022-01-31 22:11 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
>          </ul>
Сейчас при выводе каждой строчки с почтой при каждом рендеринге перебирается весь массив отфильтрованных почт. Лучше избегать реализации логики работы компонента в шаблоне, оставляя его описанием представления. Особенно, когда логика может быть не очень производительной.

2022-02-01 14:45 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-01 15:22 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-01 15:22 UTC, merged